steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - 'divine-will-cluster'
  - '--zone=us-central1-a'
  - '--project=divine-will-school'
  id: 'Get cluster credentials'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  id: 'Apply Kubernetes manifests'

# Add more steps as needed for your specific deployment process

options:
  logging: CLOUD_LOGGING_ONLY