apiVersion: v1
kind: Service
metadata:
  name: divine-will-school-service
spec:
  type: LoadBalancer
  loadBalancerIP: 34.54.95.206
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: divine-will-website